### ISSUE TITLE
Add logging for plugins

### ISSUE THREAD

**Issue by swaptr** [cln-reckless/reckless.rs#5]
During repository setup, plugins that are installed should be logged for easy and convenient access.

**Comment by swaptr** [comment]
Issue here: https://github.com/cln-reckless/reckless.rs/pull/4#discussion_r1022954348

**Comment by vincenzopalazzo** [comment]
This is an example of how to configure the log https://github.com/lnspec-tools/lncodegen.rs/blob/456bdde58bcccf559a52de3affebc3c8db6a57ab/codegen/Cargo.toml#L10-L11
